version: "{build}"

configuration: Release

build_script:
  # build test
  - mkdir %APPVEYOR_BUILD_FOLDER%\build_test
  - cd %APPVEYOR_BUILD_FOLDER%\build_test
  - cmake -G "Visual Studio 14 2015 Win64" ../dlib/test
  - cmake --build . --config %CONFIGURATION% --target dtest -- /m /verbosity:minimal
  # build examples
  - mkdir %APPVEYOR_BUILD_FOLDER%\build_examples
  - cd %APPVEYOR_BUILD_FOLDER%\build_examples
  - cmake -G "Visual Studio 14 2015 Win64" ../examples
  - cmake --build . --config %CONFIGURATION% -- /m /verbosity:minimal

test_script:
  # run test
  - cd %APPVEYOR_BUILD_FOLDER%\build_test\%CONFIGURATION%
  - dtest --runall