version: "{build}"

configuration: Release

image: Visual Studio 2017

build_script:
  # build test
  - mkdir %APPVEYOR_BUILD_FOLDER%\build_examples
  - cd %APPVEYOR_BUILD_FOLDER%\build_examples
  #- cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ../examples
  - cmake -G "Visual Studio 15 2017 Win64" -T host=x64 ../examples
  - cmake --build . --config %CONFIGURATION% 

test_script:
  # run test
