set(WEBP_FOUND False)

find_path(WEBP_INCLUDE_DIR NAMES webp/decode.h)
find_library(WEBP_LIBRARY NAMES webp)

if(WEBP_INCLUDE_DIR AND WEBP_LIBRARY)
    mark_as_advanced(WEBP_INCLUDE_DIR WEBP_LIBRARY)
    set(WEBP_FOUND True)
    set(WEBP_LIBRARIES ${WEBP_LIBRARY})
    set(WEBP_INCLUDE_DIRS ${WEBP_INCLUDE_DIR})
    message(STATUS "Found WEBP: ${WEBP_LIBRARY}")

    add_library(WEBP::WEBP UNKNOWN IMPORTED GLOBAL)
    set_target_properties(WEBP::WEBP PROPERTIES
        IMPORTED_LOCATION "${WEBP_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${WEBP_INCLUDE_DIR}"
    )
endif()
