name: Matlab

on:
  push:
    branches:
    - master
    paths:
    - ".github/workflows/build_matlab.yml"
    - "**.cpp"
    - "**.h"
    - "**.c"
    - "**.cu"
    - "**.cmake"
    - "**CMakeLists.txt"
  pull_request:
    branches:
    - master
    paths:
    - ".github/workflows/build_matlab.yml"
    - "**.cpp"
    - "**.h"
    - "**.c"
    - "**.cu"
    - "**.cmake"
    - "**CMakeLists.txt"

defaults:
  run:
    shell: bash
    working-directory: dlib


jobs:
  mex-wrapper:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1
    - name: Compile mex wrappers 
      run: |
        cmake ${{ github.workspace }}/dlib -B build -DDLIB_BUILD_MATLAB=ON
        cmake --build build --config Release --target example_mex_function example_mex_callback example_mex_struct example_mex_class --parallel 4
        cmake --install build --component Matlab --prefix ${{ github.workspace }}/dlib/matlab
    - name: Run example script
      uses: matlab-actions/run-command@v1
      with:
        command: cd dlib/matlab; example


